### ISSUE TITLE
Custom colors for histogram and/or scatter plot

### ISSUE THREAD

**Issue by bow** [sndrtj/afplot#1]
The defaults are quite ok, but it would be nicer if users can also set the plot colors via a command line flag.

**Comment by sndrtj** [comment]
That's a good idea, thanks :-).

**Comment by sndrtj** [comment]
Commit a08767f adds an optional `--color-palette` flag. It must be passed the name of a matplotlib palette. The amount of colors per palette is selected based on the number of categories present.
